### ISSUE TITLE
Make iterators `Send`

### ISSUE THREAD

**Issue by owenthewizard** [LoganDark/imgref-iter#2]
Similar to [this commit](https://github.com/kornelski/imgref/commit/d2741f53793d77c5b9e8ca33d1e499b8ff3cb2c5) in imgref, can this be done here with `IterColsMut` and friends?

**Comment by LoganDark** [comment]
`const`/shared iterators are already Send when T is Sync, and `mut` iterators are already Send when T is Send :)

I actually think imgref's ImgRefIterator is unsound because it can be sent across threads and return references to something that is not Sync. cc @kornelski

**Comment by LoganDark** [comment]
Actually, `IterColsMut`/`IterRowsMut` specifically may not actually be Send/Sync even though they should be. I'm going to fix this specific case.

**Comment by LoganDark** [comment]
Maybe `imgref` should impl Send/Sync (when sound) for `Img<*const [T]>` and `Img<*mut [T]>`
